version: "3"
services:
  app:
    image: golang:1.18-alpine
    working_dir: /app
    volumes:
      - ./:/app
    depends_on:
      - postgre
    environment:
      - GO111MODULE=on
      - CGO_ENABLED=1
      - GOOS=linux
      - GOARCH=amd64
    command: go run /app/cmd/app/parser.go
  postgre:
    image: postgres:10.11
    container_name: postgre
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=parser
    ports:
      - "5432:5432"