postgres:
  url: 'localhost'
  port: '5432'
  user: 'postgres'
  password: 'password'
  database: 'parser'
app:
  tickersInterval: 1 #min
  pricesInterval: 1 
  coinParseInterval: 60
  tickersLinkInterval: 60
logger:
  sqlLoggerLogLevel: 3 # 1: Silent,2: Error, 3: Warn, 4: Info
  appLoggerLogLevel: 4