postgres:
  url: 'localhost'
  port: '5432'
  user: 'postgres'
  password: 'password'
  database: 'parser'
app:
  tickersInterval: 1 #min
  pricesInterval: 1 
  coinParseInterval: 60
  tickersLinkInterval: 60